data_config:
  chunk:
    law_dir: test_data/laws
    node_path: chunking/golden/nodes.json
    tax_data_path: test_data/experiments/hf_tax_prompt_v2_10.csv
    wangchan_data_path: test_data/hf_wcx.csv
    section_idx_path: dump/section_idx.json

retriever_config:
  human-finetuned-bge-m3:
    model_name: wangchan-rerank-multi
    k: 10

augmenter_config:
  no-ref:
    reference: false

llm_config:
  qwen:
    model: qwen2.5:7b
    max_tokens: 2048
    temperature: 0.0
    seed: 42
    base_url: http://localhost:11434/v1
    api_key: ollama

prompt_version: v2
output_path: results/current/section_based_rag_prompt_v2_test_saved_retrieval
saved_retrieval_path: results/current/retrieval_evaluation/section_based_no_ref/retrieval_results.json
batch_size: 1
device: 0
